'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Prenommer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _800px_Beato_angelico__predella_della_pala_di_fiesole_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("800px-Beato_angelico,_predella_della_pala_di_fiesole_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _80x15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_80x15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property AddDatabase_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AddDatabase_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property address() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("address", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property beos() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("beos", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property DocumentError_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocumentError_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property DocumentOK_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocumentOK_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property EditDocument_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EditDocument_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Exit_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exit_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ExportToExcel_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExportToExcel_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property FolderOpened_16x_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FolderOpened_16x-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property GenerateFile_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GenerateFile_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property HTMLFile_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HTMLFile_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property HTMLFile_16x_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HTMLFile_16x_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Image_16x_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Image_16x_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ImportFile_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImportFile_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property InformationSymbol_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InformationSymbol_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property MSHelpIndexFile_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MSHelpIndexFile_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Public ReadOnly Property NextDocument_16x1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("NextDocument_16x1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property prenommer2_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prenommer2_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Process_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Process_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property RunUpdate_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RunUpdate_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property SearchAndApps_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SearchAndApps_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TextFile_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextFile_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property VBLightSwitch_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VBLightSwitch_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property XMLFile_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("XMLFile_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
