// ------------------------------------------------------------------------------
// <auto-generated>
// Ce code a été généré par un outil.
// Version du runtime :4.0.30319.42000
// 
// Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
// le code est régénéré.
// </auto-generated>
// ------------------------------------------------------------------------------


using System.Diagnostics;
using System.Drawing;
using System.Runtime.CompilerServices;
using Microsoft.VisualBasic;

namespace Prenommer.My.Resources
{

    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    /// <summary>
    /// Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    [HideModuleName()]
    public static class Resources
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("Prenommer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Remplace la propriété CurrentUICulture du thread actuel pour toutes
        /// les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap _800px_Beato_angelico__predella_della_pala_di_fiesole_02
        {
            get
            {
                var obj = ResourceManager.GetObject("800px-Beato_angelico,_predella_della_pala_di_fiesole_02", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap _80x15
        {
            get
            {
                var obj = ResourceManager.GetObject("_80x15", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap AddDatabase_16x
        {
            get
            {
                var obj = ResourceManager.GetObject("AddDatabase_16x", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap address
        {
            get
            {
                var obj = ResourceManager.GetObject("address", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap DocumentError_16x
        {
            get
            {
                var obj = ResourceManager.GetObject("DocumentError_16x", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap DocumentOK_16x
        {
            get
            {
                var obj = ResourceManager.GetObject("DocumentOK_16x", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap EditDocument_16x
        {
            get
            {
                var obj = ResourceManager.GetObject("EditDocument_16x", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Exit_16x
        {
            get
            {
                var obj = ResourceManager.GetObject("Exit_16x", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ExportToExcel_16x
        {
            get
            {
                var obj = ResourceManager.GetObject("ExportToExcel_16x", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap FolderOpened_16x_1
        {
            get
            {
                var obj = ResourceManager.GetObject("FolderOpened_16x-1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap GenerateFile_16x
        {
            get
            {
                var obj = ResourceManager.GetObject("GenerateFile_16x", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap HTMLFile_16x
        {
            get
            {
                var obj = ResourceManager.GetObject("HTMLFile_16x", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap HTMLFile_16x_1
        {
            get
            {
                var obj = ResourceManager.GetObject("HTMLFile_16x_1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Image_16x_1
        {
            get
            {
                var obj = ResourceManager.GetObject("Image_16x_1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ImportFile_16x
        {
            get
            {
                var obj = ResourceManager.GetObject("ImportFile_16x", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap InformationSymbol_16x
        {
            get
            {
                var obj = ResourceManager.GetObject("InformationSymbol_16x", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap MSHelpIndexFile_16x
        {
            get
            {
                var obj = ResourceManager.GetObject("MSHelpIndexFile_16x", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        /// </summary>
        public static Icon NextDocument_16x
        {
            get
            {
                var obj = ResourceManager.GetObject("NextDocument_16x", resourceCulture);
                return (Icon)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap prenommer2_2
        {
            get
            {
                var obj = ResourceManager.GetObject("prenommer2_2", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Process_16x
        {
            get
            {
                var obj = ResourceManager.GetObject("Process_16x", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap RunUpdate_16x
        {
            get
            {
                var obj = ResourceManager.GetObject("RunUpdate_16x", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap SearchAndApps_16x
        {
            get
            {
                var obj = ResourceManager.GetObject("SearchAndApps_16x", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap TextFile_16x
        {
            get
            {
                var obj = ResourceManager.GetObject("TextFile_16x", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap VBLightSwitch_16x
        {
            get
            {
                var obj = ResourceManager.GetObject("VBLightSwitch_16x", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap XMLFile_16x
        {
            get
            {
                var obj = ResourceManager.GetObject("XMLFile_16x", resourceCulture);
                return (Bitmap)obj;
            }
        }

    }
}